package:
  name: sprite4
  version: "1.0"

source:
#  git_rev: v4.0
  git_url: https://github.com/vasupsu/sprite4

requirements:
  build:
    - gcc # [linux]
    - llvmdev # [osx]
    - openmp # [linux]
    - llvm-openmp # [osx]
    - libcxx # [osx]
    - zlib
    - htslib
    - python >=2.7,<3
  run:
    - libgcc # [linux]
    - libcxx # [osx]
    - openmp # [linux]
    - llvm-openmp # [osx]
    - htslib
    - samtools
    - zlib
    - python

test:
  commands:
    - sprite4-minimap2 2>&1 | grep 'Usage'

about:
  home: https://github.com/vasupsu/sprite4
  license: BSD
