package:
  name: sprite4
  version: "1.0"

source:
#  git_rev: v4.0
  git_url: https://github.com/vasupsu/sprite4

requirements:
  build:
    - gcc
    - openmp
    - openmpi
    - zlib
    - python >=2.7,<3
  host:
    - htslib
    - zlib
  run:
    - libgcc
    - openmp
    - openmpi
    - htslib
    - samtools
    - zlib
    - python

#test:
#  commands:
#    - minimap2 2>&1 | grep 'Usage'

about:
  home: https://github.com/vasupsu/sprite4
  license: BSD
