package:
  name: sprite4
  version: "1.0"

source:
#  git_rev: v4.0
  git_url: https://github.com/vasupsu/sprite4

requirements:
  build:
    - gcc
    - openmp
    - openmpi
    - zlib
    - python >=2.7,<3
  host:
    - htslib
    - zlib
  run:
    - libgcc
    - openmp
    - openmpi
    - htslib
    - samtools
    - zlib
    - python

test:
  commands:
    - sprite4 idx $PREFIX/bin/sprite4_strelka2_install/share/demo/strelka/data/NA12891_demo20.fq
    - sprite4 map -s 1 $PREFIX/bin/sprite4_strelka2_install/share/demo/strelka/data/demo20.fa $PREFIX/bin/sprite4_strelka2_install/share/demo/strelka/data/NA12891_demo20.fq
    - sprite4 sampa -s 1 $PREFIX/bin/sprite4_strelka2_install/share/demo/strelka/data/demo20.fa
    - sprite4 varcall -s 1 $PREFIX/bin/sprite4_strelka2_install/share/demo/strelka/data/demo20.fa

about:
  home: https://github.com/vasupsu/sprite4
  license: BSD
